# Generated by Django 5.2.8 on 2025-12-03 23:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='quantidade_vagas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(default='Usuário', max_length=50),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao', to='main.evento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instituicao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use (XX) XXXXX-XXXX.', regex='^\\(\\d{2}\\)\\s\\d{5}-\\d{4}$')]),
        ),
    ]
