# Generated by Django 5.2.8 on 2025-12-10 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_evento_banner_alter_evento_quantidade_vagas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AddField(
            model_name='log',
            name='acao',
            field=models.CharField(choices=[('USER_CREATE', 'Criação de usuário'), ('EVENT_CREATE', 'Cadastro de evento'), ('EVENT_UPDATE', 'Alteração de evento'), ('EVENT_DELETE', 'Exclusão de evento'), ('EVENT_API_QUERY', 'Consulta de eventos via API'), ('CERT_GENERATE', 'Geração de certificado'), ('CERT_VIEW', 'Consulta de certificado'), ('EVENT_SUBSCRIBE', 'Inscrição em evento')], default='EVENT_CREATE', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='log',
            name='extras',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='objeto_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='objeto_tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
