# Generated by Django 5.2.8 on 2025-12-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_log_options_log_acao_log_data_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='presenca_confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
